const WHUSH = {
  linkedin: 'https://www.linkedin.com/company/whush-whu-students-help/',
  instagram: 'https://www.instagram.com/whush_official/',
  paypal: 'https://www.paypal.com/paypalme/whushev',
  whuPage: 'https://www.whu.edu/de/ueber-die-whu/campusleben/studentische-initiativen/whu-studenten-helfen/'
};
const projects = [
 {slug:'learning-spaces',title:'Charity Concert',year:'Every Winter',img:'assets/charity-concert-2.jpg',short:'Our annual christmas charity concert in Vallendar.<br>This year on the 25th November!',desc:'WHUSH organizes a charity concert every year in the run-up to Christmas to raise funds for local and international social projects. This special musical event on our campus provides a platform for students, faculty and the local community to unite for a good cause. Our concert features renowned local artists as well as talented WHU students to present a diverse musical program. All proceeds from the evening will go directly to selected charitable organizations to support their vital work.',images:['assets/charity-concert-2.jpg','assets/charity-concert-1.jpg','assets/charity-concert-3.jpg','assets/charity-concert-4.jpg']},
 {slug:'rhine-clean-up',title:'Rhine Clean-Up',year:'Every Year',img:'assets/rhine-cleanup-1.jpg',short:'Cleaning the Rhine in Vallendar together with SensAbility!',desc:'Traditionally, we are also actively involved in local environmental protection and take part in the annual Rhine CleanUp. At this event, we collect garbage together as students along the banks of the Rhine.<br><br>Every year, huge amounts of waste end up in our oceans, with much of it being transported via rivers such as the Rhine. Especially in Asia, but also in Europe, plastic pollutes our nature. With the Rhine CleanUp, we want to rid the Rhine of waste from its source to its mouth and raise people\'s awareness of the importance of not carelessly throwing away garbage. Our aim is to help keep the banks of the Rhine clean and protect natural habitats.',images:['assets/rhine-cleanup-1.jpg','assets/rhine-cleanup-2.jpg','assets/rhine-cleanup-3.jpg']},
 {slug:'digital-learning',title:'WHU Campus School Rwanda',year:'',img:'assets/campus-school-rwanda.jpg',short:'Projects creating access to education and more',desc:'Together with the Lions Club Vallendar WHU, we are committed to the education of children in Rwanda. Together, we are committed to building and equipping a school in Rwanda to give the children there access to education. Education is a crucial key to the future of these children and opens up new prospects and opportunities for them. Our initiative aims to achieve a sustainable improvement in the local education situation and thus make a positive contribution to the development of the community. By joining forces, we want to improve the children\'s quality of life and give them the opportunity to realize their dreams.'},
 {slug:'valentines-gifting',title:'Valentine’s Gifting',year:'Every Valentine’s Day',img:'assets/valentines-gifting-1.jpg',short:'Rose gifting on Valentine’s Day for Charity',desc:'Ahead of Valentine’s Day, students and members of the WHU community can purchase a rose to send to a friend, colleague, or someone special, along with a personal note. WHUSH will organize the distribution of the roses on campus, and all profits from the initiative will be donated to support WHUSH’s charity projects.',images:['assets/valentines-gifting-1.jpg','assets/valentines-gifting-2.jpg']},
 {slug:'nikolaus-gifting',title:'Nikolaus Gifting',year:'',img:'assets/nikolaus-gifting-1.jpeg',short:'Chocolate Nikolaus gifting for a good cause',desc:'For St. Nicholas Day, members of the WHU community can purchase a chocolate Nikolaus to gift to a friend, colleague, or someone special, together with a personal note. WHUSH will organize the distribution on campus. All profits from the initiative will be donated to support WHUSH’s charity projects.',images:['assets/nikolaus-gifting-1.jpeg','assets/nikolaus-gifting-2.jpeg','assets/nikolaus-gifting-3.jpeg']},
 {slug:'manuel-neuer-kids-foundation',title:'Manuel Neuer Kids Foundation',year:'',short:'Regional project supporting kids by giving them a safe place to meet, have fun, and grow.',desc:'The Manuel Neuer Kids Foundation is a regional project that supports children by helping create a safe and welcoming place where they can meet, spend time together, have fun, and receive support.'},
 {slug:'accion-misericordia',title:'Acción Misericordia',year:'',short:'Supporting a children’s home in Bogotá, Colombia',desc:'Acción Misericordia supports a children’s home in Bogotá, Colombia, by collecting donations for essential school supplies and facility improvements. Through this project, WHUSH aims to contribute to better learning conditions and a more supportive environment for the children.'},
 {slug:'christmas-market-initiative',title:'Christmas Market Initiative',year:'',short:'Mulled wine and waffles stall at the Vallendar Christmas market supporting our projects.',desc:'One of our local activities also includes running a mulled wine and waffles stall at the Vallendar Christmas market. Of course, the focus here is on the proceeds, which go directly towards supporting our projects, but the exchange with the people of Vallendar also ensures enriching and lively discussions every time, which strengthen the community and create a wonderful atmosphere.'}
];
function nav(active=''){
 return `<header class="nav"><div class="nav-inner"><a href="index.html"><img src="assets/logo.png" class="logo" alt="WHUSH"></a><nav class="links"><a data-label="Home" class="${active==='home'?'active':''}" href="index.html"><span>Home</span></a><a data-label="Projects" class="${active==='projects'?'active':''}" href="projects.html"><span>Projects</span></a><a data-label="Team" class="${active==='team'?'active':''}" href="team.html"><span>Team</span></a><a data-label="Donate" class="nav-donate" target="_blank" rel="noreferrer" href="${WHUSH.paypal}"><span>Donate</span></a></nav><a class="pill" href="#footer">Contact</a></div></header>`
}
function footer(){return `<footer id="footer" class="footer"><div class="footer-content"><div class="small">LET'S CONNECT!</div><div class="footer-email">whush@whu.edu</div><div class="footer-grid"><div class="address"><strong>Address</strong><br>WHU Students help e.V.<br>Burgplatz 2<br>56179 Vallendar<br>Germany</div><div class="footer-col"><strong>Socials</strong><a target="_blank" href="${WHUSH.linkedin}">Linkedin</a><a target="_blank" href="${WHUSH.instagram}">Instagram</a><a target="_blank" href="${WHUSH.paypal}">Paypal</a><a target="_blank" href="${WHUSH.whuPage}">WHU Initiative Page</a><a target="_blank" href="https://www.whu.edu/">whu.edu</a></div><div class="footer-col"><strong>Pages</strong><a href="index.html">Home</a><a href="projects.html">Project</a><a href="team.html">Team</a><a target="_blank" rel="noreferrer" href="${WHUSH.paypal}">Donate</a></div></div><div class="footer-bottom"><img class="footer-logo" src="assets/logo-white.png" alt="WHUSH"><div class="footer-bottom-right"><a class="footer-legal-btn" href="impressum.html">Impressum</a><a class="footer-legal-btn" href="datenschutz.html">Datenschutz</a><div class="copy">© 2026 WHUSH e.V. All rights reserved.</div></div></div></div></footer>`}
function projectCard(p){return `<a class="card project-card-${p.slug} ${p.img?'':'card-no-image'}" href="project.html?project=${p.slug}">${p.img?`<img src="${p.img}" alt="${p.title}">`:''}<div class="card-body"><div class="card-line"><h3>${p.title}</h3>${p.year?`<span class="year">${p.year}</span>`:''}</div><p>${p.short}</p></div></a>`}
function renderCommon(active){
  document.body.insertAdjacentHTML('afterbegin',nav(active));
  const addFooter = () => {
    if (!document.getElementById('footer')) {
      document.body.insertAdjacentHTML('beforeend', footer());
    }
  };
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', addFooter);
  } else {
    addFooter();
  }
}
